from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class Todo:
    """
    Represents a single todo item with all required fields.
    
    Attributes:
        id: Unique identifier for each todo, auto-generated by repository layer
        title: The main text of the todo (1-150 characters, required)
        description: Additional details about the todo (optional)
        status: Current state of the todo ("pending" or "completed", default: "pending")
        created_at: Timestamp when the todo was created (auto-set on creation)
        updated_at: Timestamp when the todo was last modified (auto-updated on modification)
    """
    id: int
    title: str
    description: Optional[str] = None
    status: str = "pending"  # Default to "pending"
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        """Validate the todo after initialization."""
        if not self.title.strip():
            raise ValueError("Title cannot be empty")
        
        if len(self.title) > 150:
            raise ValueError(f"Title exceeds maximum length of 150 characters: {len(self.title)} provided")
        
        if self.status not in ["pending", "completed"]:
            raise ValueError(f"Status must be 'pending' or 'completed', got '{self.status}'")
        
        # Ensure updated_at is always at least as recent as created_at
        if self.updated_at < self.created_at:
            self.updated_at = self.created_at

    def mark_completed(self) -> None:
        """Mark the todo as completed."""
        self.status = "completed"
        self.updated_at = datetime.now()

    def mark_pending(self) -> None:
        """Mark the todo as pending."""
        self.status = "pending"
        self.updated_at = datetime.now()

    def update_title(self, new_title: str) -> None:
        """Update the title of the todo."""
        if not new_title.strip():
            raise ValueError("Title cannot be empty")
        
        if len(new_title) > 150:
            raise ValueError(f"Title exceeds maximum length of 150 characters: {len(new_title)} provided")
        
        self.title = new_title
        self.updated_at = datetime.now()

    def update_description(self, new_description: Optional[str]) -> None:
        """Update the description of the todo."""
        self.description = new_description
        self.updated_at = datetime.now()